### ISSUE TITLE
timer failure: attempt to call a number value

### ISSUE THREAD

**Issue by whitehatboxer** [Kong/lua-resty-healthcheck#108]
Today I started deploying my Openresty project, I used `lua-resty-healthcheck` with version = 2.0.0-1 in this project. 

 I found many error logs which printed by my app code and caused by [this line in the github project](https://github.com/Kong/lua-resty-healthcheck/blob/50573b31ffd06ef460f085e383fdbde24765c37c/lib/resty/healthcheck.lua#L521). And code snippets around was also displayed below.
```lua
--- Get the current status of the target.
-- @param ip IP address of the target being checked.
-- @param port the port being checked against.
-- @param hostname the hostname of the target being checked.
-- @return `true` if healthy, `false` if unhealthy, or `nil + error` on failure.
function checker:get_target_status(ip, port, hostname)

  local target = get_target(self, ip, port, hostname)
  if not target then
    return nil, "target not found"
  end
  return target.internal_health == "healthy"
      or target.internal_health == "mostly_healthy"

end
```

It seemed function `get_target` failed, so I deep into code and found it was that self.targets was nil when call this function `get_target_status`. But the root reasons was still unknown.

I spent almost the whole afternoon to deal with it. Finally I found some abnormal error log in my Nginx error_logs. It said `timer failure: attempt to call a number value`.
![image](https://user-images.githubusercontent.com/18637307/173081718-5f78d88d-b743-4c61-b256-fe665e231df8.png)

I read the source code again and found [this snippets](https://github.com/Kong/lua-resty-healthcheck/blob/50573b31ffd06ef460f085e383fdbde24765c37c/lib/resty/healthcheck.lua#L197) which may be related to it. 
![image](https://user-images.githubusercontent.com/18637307/173084666-c3ab9a5b-0aa8-4013-9020-faf30f918485.png)

I doubt that `pcall(args[1] ...)` here was a bug. When `ngx_timer_at` was called, the args[1] will always be parameter **delay**. So
the call `ngx_timer_at` always failed, then Lua thread failed get target_list from nginx shm, and self.targets will be empty at last.

BTW, I found this error in my Nginx server which has 24 workers firstly. And I reproduced this error locally with another Nginx server which has 5 workers. This error seems occureed in Nginx server with more than one workers.

**Comment by kikito** [comment]
Hello, a very typical Lua problem when `self` is `nil` is in the code calling the function in question.

My suspicion is that somewhere in your code you are calling `get_target_status` with a dot (`checker.get_target_status`) instead of a colon (`checker:get_target_status`). The dot will not fill up `self`, while the colon will.
