### ISSUE TITLE
The version of lua-resty-worker-events

### ISSUE THREAD

**Issue by monkeyDluffy6017** [Kong/lua-resty-healthcheck#143]
The latest version of lua-resty-worker-events is 2.0.1 (https://github.com/Kong/lua-resty-worker-events/releases/tag/2.0.1),
And you are testing with the version 1.0.0 (https://github.com/Kong/lua-resty-healthcheck/blob/release/1.6.x/.github/workflows/build_and_test_with_worker_events.yml#L46C59-L46C59),
Do you have a plan to upgrade the lua-resty-worker-events?
Is kong already using the latest version of lua-resty-worker-events?

**Comment by chronolaw** [comment]
lua-resty-worker-events is no longer maintained, we are using a new library lua-resty-events.
See: https://github.com/Kong/lua-resty-events
