### ISSUE TITLE
When multiple targets have the same IP:PORT, active healthcheck results for one impact them all

### ISSUE THREAD

**Issue by rsbrisci** [Kong/lua-resty-healthcheck#17]
When routing to multiple separate application with the same IP:PORT for ingress (as in an HA-proxy), I notice that healthcheck results for the original targets seem to be ignored as I add new ones.

This impacts us heavily, as most of our APIs are deployed to a kubernetes cluster, all of which has the same IP:PORT for ingress (the host header is used to determine which specific service to send traffic to at the cluster's ingress router).

Request adding logic to the balancer to track each target's status as a `hostname:port` object, or `hostname:ip:port` object instead of just `ip:port` to allow separate targets to have separate status'

**Comment by Tieske** [comment]
fixed by #21
