### ISSUE TITLE
Exception!!! 'report_tcp_success()' unimplemented in healthcheck.lua

### ISSUE THREAD

**Issue by LovingLoulou** [Kong/lua-resty-healthcheck#19]
2019/05/10 12:23:29 [error] 12056#0: *195028 lua user thread aborted: runtime error: /usr/local/share/lua/5.1/resty/healthcheck.lua:737: attempt to call method 'report_tcp_success' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/resty/healthcheck.lua: in function 'run_single_check'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:798: in function </usr/local/share/lua/5.1/resty/healthcheck.lua:794>
coroutine 1:
        [C]: in function 'connect'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:726: in function 'run_single_check'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:798: in function 'run_work_package'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:826: in function 'active_check_targets'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:907: in function </usr/local/share/lua/5.1/resty/healthcheck.lua:871>, context: ngx.timer, client: 127.0.0.1, server: 127.0.0.1:8001
2019/05/10 12:23:29 [error] 12056#0: *195028 lua user thread aborted: runtime error: /usr/local/share/lua/5.1/resty/healthcheck.lua:737: attempt to call method 'report_tcp_success' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/resty/healthcheck.lua: in function 'run_single_check'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:798: in function </usr/local/share/lua/5.1/resty/healthcheck.lua:794>
coroutine 1:
        [C]: in function 'connect'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:726: in function 'run_single_check'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:798: in function 'run_work_package'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:826: in function 'active_check_targets'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:907: in function </usr/local/share/lua/5.1/resty/healthcheck.lua:871>, context: ngx.timer, client: 127.0.0.1, server: 127.0.0.1:8001
2019/05/10 12:23:29 [error] 12056#0: *195028 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/healthcheck.lua:737: attempt to call method 'report_tcp_success' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/resty/healthcheck.lua: in function 'run_single_check'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:798: in function 'run_work_package'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:826: in function 'active_check_targets'
        /usr/local/share/lua/5.1/resty/healthcheck.lua:907: in function </usr/local/share/lua/5.1/resty/healthcheck.lua:871>, context: ngx.timer, client: 127.0.0.1, server: 127.0.0.1:8001

**Comment by Tieske** [comment]
thanks for the report.
