### ISSUE TITLE
a success will reset _all three_ failure counters doesn't work

### ISSUE THREAD

**Issue by olderwei** [Kong/lua-resty-healthcheck#6]
you have said "a success will reset _all three_ failure counters" at the beginning, but it doesn't work.
Provided the http_failures is set three times, if there are two failures and then a success, but then another failure, the target will be marked as failure.
I think the problem is that the conditional statement of incr_counter "(health_mode == "healthy" and target.healthy) or (health_mode == "unhealthy" and not target.healthy) " goes wrong

**Comment by hishamhm** [comment]
Hello @olderwei! Thanks for reporting. Indeed, I have confirmed the bug. I am working on a new release including a fix. Thank you!
