### ISSUE TITLE
failed to release lock

### ISSUE THREAD

**Issue by vaxilicaihouxian** [Kong/lua-resty-healthcheck#61]
2020/12/15 14:44:37 [error] 123#0: *60053758 [lua] healthcheck.lua:1104: log(): [healthcheck] (1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main) failed to release lock 'lua-resty-healthcheck:1bdcdd5c-ecbc-4cb3-b271-c5c4a3e03f56:ae-app-56.www.hba.main:target_list_lock': unlocked, context: ngx.timer

**Comment by Tieske** [comment]
@vaxilicaihouxian this is too little information... when creating issues like this, please add some more information to work with.

What version are you using?

**Comment by Tieske** [comment]
https://github.com/Kong/kong/issues/6687

**Comment by mcdullbloom** [comment]
@vaxilicaihouxian did this problem have been solved?
