### ISSUE TITLE
Question: How could we install this package using opm?

### ISSUE THREAD

**Issue by harighub** [Kong/lua-resty-healthcheck#63]
I'm pretty new to openresty/lua world, as I understands this library is part of luarocks wheres openresty recommending to use opm as package manager. I wonder how should I manage to make this happen to try library on openresty? Thanks

**Comment by Tieske** [comment]
we do not have OPM details, but contibutions are welcome. Until then manually copy the files into the right locations

(OpenResty recommends OPM because they wrote OPM...)
