### ISSUE TITLE
What is the difference between active and passive mode?

### ISSUE THREAD

**Issue by wfgydbu** [Kong/lua-resty-healthcheck#64]
Hi all,

I'm using this lib in our project, thanks for the great work.

I'm just a bit confused about the purpose of passive mode healthcheck, what's it design for? what's the scenario?

**Comment by Tieske** [comment]
Here are the Kong docs on it, I think these will answer your questions: https://docs.konghq.com/2.2.x/health-checks-circuit-breakers/

**Comment by wfgydbu** [comment]
Thanks.
