### ISSUE TITLE
TCP Health check is not Making upstream target unhealthy. 

### ISSUE THREAD

**Issue by puneet739** [Kong/lua-resty-healthcheck#69]
In order to reproduce this,  i created a random service and enabled tcp healthcheck to it. 
Post that i added some random IP and port which doesnt Exist. Even i dont see any error of timeout in logs, the status of upstream is never set to UNHEALTHY. 

Kong Version i am using : kong:2.1.3-centos

Below is my service configuration
`{
    "client_certificate": null,
    "created_at": 1598938985,
    "id": "a250bcbe-3934-4825-89ab-81411ee95969",
    "tags": null,
    "name": "upstream_javaapigw",
    "algorithm": "round-robin",
    "hash_on_header": null,
    "hash_fallback_header": null,
    "host_header": null,
    "hash_on_cookie": null,
    "healthchecks": {
        "threshold": 100,
        "active": {
            "unhealthy": {
                "http_statuses": [
                    429,
                    404,
                    500,
                    501,
                    502,
                    503,
                    504,
                    505
                ],
                "tcp_failures": 2,
                "timeouts": 2,
                "http_failures": 1,
                "interval": 3
            },
            "type": "tcp",
            "http_path": "/",
            "timeout": 1,
            "healthy": {
                "successes": 5,
                "interval": 1,
                "http_statuses": [
                    200,
                    302
                ]
            },
            "https_sni": null,
            "https_verify_certificate": true,
            "concurrency": 10
        },
        "passive": {
            "unhealthy": {
                "http_failures": 1,
                "http_statuses": [
                    429,
                    500,
                    503
                ],
                "tcp_failures": 1,
                "timeouts": 1
            },
            "healthy": {
                "http_statuses": [
                    200,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    207,
                    208,
                    226,
                    300,
                    301,
                    302,
                    303,
                    304,
                    305,
                    306,
                    307,
                    308
                ],
                "successes": 0
            },
            "type": "tcp"
        }
    },
    "hash_on_cookie_path": "/",
    "hash_on": "none",
    "hash_fallback": "none",
    "slots": 10000
}`

**Comment by kikito** [comment]
Hello, this seems to be a kong gateway issue and not a lua-resty-healthcheck specific issue. Please open a new issue in Kong if this problem still exists. Closing this issue.
