### ISSUE TITLE
Passive healthcheck bug

### ISSUE THREAD

**Issue by wuguangkuo** [Kong/lua-resty-healthcheck#7]
file: resty/healthcheck.lua
function: incr_counter

description:
The bug code is there:
if (health_mode == “healthy” and target.healthy) or
(health_mode == “unhealthy” and not target.healthy) then
– No need to count successes when healthy or failures when unhealthy
return true
end

When I config passive healthcheck without active healthcheck. If the failures counter of a target is not null and it’s current status is heathy, then this bug results that the success request can’t clean the failure counter。

I had resove this bug in this way:

local nokCounter = self.shm:get(get_shm_key(self.TARGET_NOKS, ip, port));
if (health_mode == “healthy” and target.healthy and (not nokCounter or nokCounter == 0)) or
(health_mode == “unhealthy” and not target.healthy) then
– No need to count successes when healthy or failures when unhealthy
return true
end

**Comment by hishamhm** [comment]
Hello @wuguangkuo! Thanks for reporting. I have confirmed the bug. I am working on a new release including a fix. Thank you!

**Comment by wuguangkuo** [comment]
hello @hishamhm ,I has commit the pull request: https://github.com/Kong/lua-resty-healthcheck/pull/8
Should I close it?

**Comment by hishamhm** [comment]
@wuguangkuo I closed it, no problem. PR #10 is an extended fix to the problem, that corrects the behavior but keeps the optimization of avoiding shm access whenever possible.
